on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: packaginganddeliverymicroservice.azurecr.io
        username: ${{ secrets.acr_packaginganddeliverymicroservice_username }}
        password: ${{ secrets.acr_packaginganddeliverymicroservice_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/PackagingAndDeliveryMicroservice" -f  "PackagingAndDeliveryMicroservice/Dockerfile" -t packaginganddeliverymicroservice.azurecr.io/returnordermanagementsystem:${{ github.sha }} --label dockerfile-path=PackagingAndDeliveryMicroservice/Dockerfile
        docker push packaginganddeliverymicroservice.azurecr.io/returnordermanagementsystem:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_returnordermanagementsystem_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep packaginganddeliverymicroservice | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace packaginganddeliverymicroservice`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: packaginganddeliverymicroservice
        container-registry-url: packaginganddeliverymicroservice.azurecr.io
        container-registry-username: ${{ secrets.acr_packaginganddeliverymicroservice_username }}
        container-registry-password: ${{ secrets.acr_packaginganddeliverymicroservice_password }}
        secret-name: returnordermdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: packaginganddeliverymicroservice
        manifests: |
          manifests/deployment-4.yml
          manifests/service-4.yml
        images: |
          packaginganddeliverymicroservice.azurecr.io/returnordermanagementsystem:${{ github.sha }}
        imagepullsecrets: |
          returnordermdockerauth
