on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n packaginganddeliverymicroservice -g packaginganddeliverymicroservicea0d3-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n packaginganddeliverymicroservice --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n packaginganddeliverymicroservice --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n packaginganddeliverymicroservice --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: packaginganddeliverymicroservice.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/PackagingAndDeliveryMicroservice" -f  "PackagingAndDeliveryMicroservice/Dockerfile" -t packaginganddeliverymicroservice.azurecr.io/returnordermanagementsystem:${{ github.sha }} --label dockerfile-path=PackagingAndDeliveryMicroservice/Dockerfile
        docker push packaginganddeliverymicroservice.azurecr.io/returnordermanagementsystem:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_returnordermanagementsystem_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep packaginganddeliverymicroservice | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace packaginganddeliverymicroservice`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: packaginganddeliverymicroservice
        container-registry-url: packaginganddeliverymicroservice.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: returnordermdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: packaginganddeliverymicroservice
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          packaginganddeliverymicroservice.azurecr.io/returnordermanagementsystem:${{ github.sha }}
        imagepullsecrets: |
          returnordermdockerauth   
