on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: componentcr.azurecr.io
        username: ${{ secrets.acr_componentcr_username }}
        password: ${{ secrets.acr_componentcr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/PackagingAndDeliveryMicroservice" -f  "PackagingAndDeliveryMicroservice/Dockerfile" -t componentcr.azurecr.io/returnordermanagementsystem:${{ github.sha }} --label dockerfile-path=PackagingAndDeliveryMicroservice/Dockerfile
        docker push componentcr.azurecr.io/returnordermanagementsystem:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_returnordermanagementsystem_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep packaging | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace packaging`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: packaging
        container-registry-url: componentcr.azurecr.io
        container-registry-username: ${{ secrets.acr_componentcr_username }}
        container-registry-password: ${{ secrets.acr_componentcr_password }}
        secret-name: returnordermdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: packaging
        manifests: |
          manifests/deployment-9.yml
          manifests/service-9.yml
          manifests/ingress-3.yml
        images: |
          componentcr.azurecr.io/returnordermanagementsystem:${{ github.sha }}
        imagepullsecrets: |
          returnordermdockerauth
