on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: returnordermanagementsystem.azurecr.io
        username: ${{ secrets.acr_returnordermanagementsystem_username }}
        password: ${{ secrets.acr_returnordermanagementsystem_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/ReturnOrderManagementSystemAPIGateway" -f  "ReturnOrderManagementSystemAPIGateway/Dockerfile" -t returnordermanagementsystem.azurecr.io/returnordermanagementsystem:${{ github.sha }} --label dockerfile-path=ReturnOrderManagementSystemAPIGateway/Dockerfile
        docker push returnordermanagementsystem.azurecr.io/returnordermanagementsystem:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_returnordermanagementsystem_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep apigateway | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace apigateway`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: apigateway
        container-registry-url: returnordermanagementsystem.azurecr.io
        container-registry-username: ${{ secrets.acr_returnordermanagementsystem_username }}
        container-registry-password: ${{ secrets.acr_returnordermanagementsystem_password }}
        secret-name: returnordermdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: apigateway
        manifests: |
          manifests/deployment-4.yml
          manifests/service-4.yml
        images: |
          returnordermanagementsystem.azurecr.io/returnordermanagementsystem:${{ github.sha }}
        imagepullsecrets: |
          returnordermdockerauth
